---
- hosts: all
  become: true

  roles:
      - role: anarchotechnyc.tor
        vars:
            onion_services:
                - name: onion_radio
                  virtports:
                      # The streaming client's port.
                      - port_number: 8000
                      # The Web browser's port.
                      - port_number: 80
                        target_port: 8000
      - role: anarchotechnyc.icecast
        vars:
            # TODO:
            # What would be great is if the earlier run of the Tor
            # Ansible role could register the actual Onion domains
            # in use. Then, we can reference them via a registered
            # variable or a fact that has been set for use here.
            icecast_hostname: "{{ onion | default('TODO') }}"
